config/routes.rb
DinnerDash::Application.routes.draw do

  resources :sales
  resources :reviews
  resources :sessions
  resources :orders, except: [:new]
  resources :users
  resources :categories
  resources :items do
    resources :reviews
  end
  resources :menu, only: [:index]

  get 'cart',                 to: 'cart#show',   as: :cart
  get 'cart/:item_id/add',    to: 'cart#add',    as: :add_item_cart
  get 'cart/:item_id/remove', to: 'cart#remove', as: :remove_item_cart

  get 'orders/:id/remove/:item_id', to: 'orders#remove_item', as: :remove_item_order
  get 'orders/:id/transition/:order_status', to: 'orders#transition', as: :transition_order

  get 'signup',  to: 'users#new'
  get 'signin',  to: 'sessions#new'
  get 'signout', to: 'sessions#destroy'

  get 'about',   to: 'marketing#about'
  get 'faqs',    to: 'marketing#faqs'

  root 'marketing#index'

end

app/models/user.rb
class User < ActiveRecord::Base

  # -------------------------------------- Plugins
  
  has_secure_password
  
  # -------------------------------------- Associations
  
  has_many :orders
  has_many :reviews
  has_many :items, through: :orders
  
  # -------------------------------------- Validations
  
  validates_presence_of :name, :email
  validates_uniqueness_of :email, case_sensitive: false
  
  # -------------------------------------- Instance Methods
  
  def has_purchased?(item)
    item_ids.include?(item.id)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authorized_for_admin?, only: [:index, :destroy, :show]
  before_action :authorized_for_self?, only: [:edit, :update], unless: :is_admin?

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Thank you for signing up!'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to root_path, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params[:user].permit!
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.input :admin if is_admin? %>

  <div class="actions">
    <br />
    <%= f.submit class: 'btn btn-primary' %>
  </div>
  
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<% if is_admin? %>
  <%= link_to 'Show', @user %> |
  <%= link_to 'Back', users_path %>
<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user_path(user) %></td>
        <td><%= mail_to user.email %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %> | <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<p><%= mail_to @user.email %></p>

<p><strong>Admin? <%= @user.admin? %></p>

<% if @user.orders.any? %>
<ul>
  <% @user.orders.each do |order| %>
    <%= content_tag :li, link_to(order.created_at, order_path(order)) %>
  <% end %>
</ul>
<% end %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>