config/routes.rb
DinnerDash::Application.routes.draw do

  resources :sales
  resources :reviews
  resources :sessions
  resources :orders, except: [:new]
  resources :users
  resources :categories
  resources :items do
    resources :reviews
  end
  resources :menu, only: [:index]

  get 'cart',                 to: 'cart#show',   as: :cart
  get 'cart/:item_id/add',    to: 'cart#add',    as: :add_item_cart
  get 'cart/:item_id/remove', to: 'cart#remove', as: :remove_item_cart

  get 'orders/:id/remove/:item_id', to: 'orders#remove_item', as: :remove_item_order
  get 'orders/:id/transition/:order_status', to: 'orders#transition', as: :transition_order

  get 'signup',  to: 'users#new'
  get 'signin',  to: 'sessions#new'
  get 'signout', to: 'sessions#destroy'

  get 'about',   to: 'marketing#about'
  get 'faqs',    to: 'marketing#faqs'

  root 'marketing#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  
  include ActionView::Helpers::NumberHelper 
  
  # -------------------------------------- Validations
  
  validates_presence_of :title
  validates_presence_of :description
  validates :price, numericality: { only_integer: true, greater_than: 0 }
  validates_uniqueness_of :title, case_sensitive: false
  
  # -------------------------------------- Scopes
  
  scope :active, -> { where(active: true) }
  
  # -------------------------------------- Callbacks
  
  before_create do
    self.prep_time ||= 12
  end
  
  # -------------------------------------- Associations
  
  belongs_to :category, counter_cache: true
  belongs_to :sale, counter_cache: true
  has_and_belongs_to_many :orders
  has_many :reviews
  
  # -------------------------------------- Instance Methods
  
  def average_rating
    reviews.average(:rating).try(:round, 1)
  end
  
  def display_price
    if on_sale?
      "<s style='color:red'>#{number_to_currency(price)}</s> #{number_to_currency(calculated_price)}"
    else
      number_to_currency(price)
    end
  end

  def calculated_discount
    if on_sale?
      price.to_f * (sale.discount.to_f / 100.to_f)
    else
      0
    end
  end
  
  def calculated_price
    if on_sale?
      price.to_f - calculated_discount
    else
      price
    end
  end

  def on_sale?
    sale.present? && sale.active?
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_review, only: [:show]
  before_action :authorized_for_admin?, except: [:show]

  # GET /items
  # GET /items.json
  def index
    @items = Item.paginate(page: params[:page], per_page: per_page)
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @reviews = @item.reviews.paginate(page: params[:page], per_page: per_page)
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to items_path, notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params[:item].permit!
    end
  
    def set_review
      @review = Review.new(item_id: @item.id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= simple_form_for(@item) do |f| %>

  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :active %>
  <%= f.input :price %>
  <%= f.input :photo %>
  <%= f.input :prep_time %>
  <%= f.association :category %>
  <%= f.association :sale %>

  <div class="actions">
    <br />
    <%= f.submit class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/items/_item.html.erb
<li class="list-group-item">
  <%= link_to item.title, item_path(item) %> 
  (<%= link_to 'Add to Cart', add_item_cart_path(item), class: 'text-success' %>) 
  <span class="text-muted"><%= truncate item.description, length: 80 %></span>
  <span class="badge"><%= item.display_price.html_safe %></span>
</li>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>All Items</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th>Active?</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= link_to item.title, item_path(item) %></td>
        <td><%= number_to_currency item.price %></td>
        <td><%= item.active? ? 'Yes' : 'No' %>
        <td><%= link_to 'Edit', edit_item_path(item) %> | <%= link_to 'Delete', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p><%= link_to 'New Item', new_item_path %></p>

<%= will_paginate @items, renderer: BootstrapPagination::Rails %>

app/views/items/new.html.erb
<h1>Create a new item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<h1><%= @item.title %> <span class="badge"><%= @item.display_price.html_safe %></span></h1>

<% if @item.category %>
  <p><strong>Category: </strong><%= @item.category.title %></p>
<% end %>

<%= image_tag @item.photo, class: 'thumbnail' if @item.photo.present? %>

<p><%= @item.description %></p>

<% if @item.active? %>
  <p><%= link_to 'Add to Cart', add_item_cart_path(@item), class: 'btn btn-primary' %></p>
<% end %>

<% if is_admin? %>
  <%= link_to 'Edit', edit_item_path(@item) %> |
  <%= link_to 'Back', items_path %>
<% end %>

<h2>Reviews <% if @item.reviews.any? %>(Average rating: <%= @item.average_rating %> stars)<% end %></h2>
<%= page_entries_info @reviews %>
<hr />
<%= render @reviews %>
<%= will_paginate @reviews, renderer: BootstrapPagination::Rails %>

<h4>Add a Review</h4>
<% if user_signed_in? %>
  <% if current_user.has_purchased?(@item) %>
    <%= render 'reviews/form' %>
  <% else %>
    <p>You must order the item before you may add a review.</p>
  <% end %>
<% else %>
  <p><%= link_to('Sign in', signin_path) %> to add a review.</p>
<% end %>