config/routes.rb
DinnerDash::Application.routes.draw do

  resources :sales
  resources :reviews
  resources :sessions
  resources :orders, except: [:new]
  resources :users
  resources :categories
  resources :items do
    resources :reviews
  end
  resources :menu, only: [:index]

  get 'cart',                 to: 'cart#show',   as: :cart
  get 'cart/:item_id/add',    to: 'cart#add',    as: :add_item_cart
  get 'cart/:item_id/remove', to: 'cart#remove', as: :remove_item_cart

  get 'orders/:id/remove/:item_id', to: 'orders#remove_item', as: :remove_item_order
  get 'orders/:id/transition/:order_status', to: 'orders#transition', as: :transition_order

  get 'signup',  to: 'users#new'
  get 'signin',  to: 'sessions#new'
  get 'signout', to: 'sessions#destroy'

  get 'about',   to: 'marketing#about'
  get 'faqs',    to: 'marketing#faqs'

  root 'marketing#index'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_item
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :authorized_for_user?, only: [:edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = @item.reviews.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = @item.reviews.build
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = @item.reviews.build(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @item, notice: 'Review was successfully created.' }
        format.json { render action: 'show', status: :created, location: @review }
      else
        format.html { render action: 'new' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @item, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to @item }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = @item.reviews.find(params[:id])
    end

    def set_item
      @item = Item.find(params[:item_id])
    end
  
    def authorized_for_user?
      redirect_to root_path, alert: 'Not authorized!' unless user_signed_in? && (current_user.id == @review.user_id)
    end
  
    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params[:review].permit!
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= simple_form_for([@item, @review]) do |f| %>

  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :title %>
  <%= f.input :body %>
  <%= f.input :rating, as: :select, collection: Review.ratings %>
  <%= f.hidden_field :user_id, value: current_user.id if user_signed_in? %>

  <div class="actions">
    <br />
    <%= f.submit class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/reviews/_review.html.erb
<%= content_tag :h4, "#{review.title} (#{review.rating} stars)" %>
<%= content_tag :p, review.body %>
<%= content_tag :cite, review.user.name %>
<%= link_to 'Edit', edit_item_review_path(@item, review) if review.editable_for?(current_user) %>
<hr />

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>