config/routes.rb
DinnerDash::Application.routes.draw do

  resources :sales
  resources :reviews
  resources :sessions
  resources :orders, except: [:new]
  resources :users
  resources :categories
  resources :items do
    resources :reviews
  end
  resources :menu, only: [:index]

  get 'cart',                 to: 'cart#show',   as: :cart
  get 'cart/:item_id/add',    to: 'cart#add',    as: :add_item_cart
  get 'cart/:item_id/remove', to: 'cart#remove', as: :remove_item_cart

  get 'orders/:id/remove/:item_id', to: 'orders#remove_item', as: :remove_item_order
  get 'orders/:id/transition/:order_status', to: 'orders#transition', as: :transition_order

  get 'signup',  to: 'users#new'
  get 'signin',  to: 'sessions#new'
  get 'signout', to: 'sessions#destroy'

  get 'about',   to: 'marketing#about'
  get 'faqs',    to: 'marketing#faqs'

  root 'marketing#index'

end

app/models/cart.rb
class Cart
  
  include ItemCalculation
  
  def initialize(session)
    @session = session
    @session[:item_ids] ||= []
  end

  # -------------------------------------- Instance Methods

  def add_item(item)
    @session[:item_ids] << item.id
  end

  def remove_item(item)
    @session[:item_ids].delete(item.id)
  end

  def items
    @items ||= begin
      returned_items = Item.where(id: item_ids)
      collected_items = returned_items.clone.clear
      item_ids.each do |i|
        collected_items << returned_items.detect { |d| d.id == i.to_i }
      end
      collected_items
    end
  end

  def item_ids
    @session[:item_ids]
  end

  def items_count
    @session[:item_ids].size
  end

  def empty?
    @session[:item_ids].empty?
  end

  def empty!
    @session[:item_ids] = []
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  
  # -------------------------------------- Validations
  
  validates_presence_of :title
  
  # -------------------------------------- Associations
  
  has_many :items
  
end

app/models/item.rb
class Item < ActiveRecord::Base
  
  include ActionView::Helpers::NumberHelper 
  
  # -------------------------------------- Validations
  
  validates_presence_of :title
  validates_presence_of :description
  validates :price, numericality: { only_integer: true, greater_than: 0 }
  validates_uniqueness_of :title, case_sensitive: false
  
  # -------------------------------------- Scopes
  
  scope :active, -> { where(active: true) }
  
  # -------------------------------------- Callbacks
  
  before_create do
    self.prep_time ||= 12
  end
  
  # -------------------------------------- Associations
  
  belongs_to :category, counter_cache: true
  belongs_to :sale, counter_cache: true
  has_and_belongs_to_many :orders
  has_many :reviews
  
  # -------------------------------------- Instance Methods
  
  def average_rating
    reviews.average(:rating).try(:round, 1)
  end
  
  def display_price
    if on_sale?
      "<s style='color:red'>#{number_to_currency(price)}</s> #{number_to_currency(calculated_price)}"
    else
      number_to_currency(price)
    end
  end

  def calculated_discount
    if on_sale?
      price.to_f * (sale.discount.to_f / 100.to_f)
    else
      0
    end
  end
  
  def calculated_price
    if on_sale?
      price.to_f - calculated_discount
    else
      price
    end
  end

  def on_sale?
    sale.present? && sale.active?
  end
  
end

app/models/order.rb
class Order < ActiveRecord::Base
  
  include ItemCalculation
  
  # -------------------------------------- Associations

  belongs_to :user
  has_and_belongs_to_many :items

  # -------------------------------------- Validations

  validates_presence_of :user_id
  validate :minimum_order_size
  validate :earliest_pickup_at, on: :create
  validate :open_for_business, on: :create

  # -------------------------------------- Scopes

  scope :with_status, -> (status) { where(order_status: status) }

  # -------------------------------------- Callbacks

  # When a new order is saved, automatically set
  # the default order status
  before_validation(on: :create) do
    self.pickup_at  ||= Time.zone.now + 15.minutes
    self.order_status = Order.order_statuses.first
  end

  after_create do
    OrderMailer.new_message(self).deliver
  end
  
  # -------------------------------------- Instance Methods

  def minimum_order_size
    errors.add(:items, 'must contain at least one') if items.none?
  end

  def earliest_pickup_at
    errors.add(:pickup_at, 'must be further in the future') if pickup_at < calculate_earliest_pickup_at
  end

  def open_for_business
    unless (9..17).include?(pickup_at.hour)
      errors.add(:pickup_at, 'is while the kitchen is closed, please select a time between 9am and 5pm')
    end
  end

  def cancelable?
    Order.order_statuses[0..1].include? order_status
  end

  def ordered?
    order_status == 'ordered'
  end

  def paid?
    order_status == 'paid'
  end

  # -------------------------------------- Class Methods

  def self.order_statuses
    ['ordered', 'paid', 'cancelled', 'completed']
  end

  def self.order_statuses_for_select
    order_statuses.collect { |o| [o.humanize, o] }.unshift(['Show All', ''])
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  
  # -------------------------------------- Associations
  
  belongs_to :user
  belongs_to :item
  
  # -------------------------------------- Scopes
  
  default_scope order('reviews.rating DESC')
  
  # -------------------------------------- Validations
  
  validates_presence_of :user_id, :item_id, :title, :body, :rating
  validates_inclusion_of :rating, in: 1..5
  validate :user_can_update, on: :update
  
  # -------------------------------------- Instance Methods
  
  def user_can_update
    errors.add(:created_at, 'must be within the last 15 minutes') unless editable?
  end
  
  def editable?
    created_at > 15.minutes.ago
  end
  
  def editable_for?(current_user)
    editable? && current_user.present? && current_user == user
  end
  
  # -------------------------------------- Class Methods
  
  def self.ratings
    1..5
  end
  
end

app/models/sale.rb
class Sale < ActiveRecord::Base

  # -------------------------------------- Associations

  has_many :items

end

app/models/user.rb
class User < ActiveRecord::Base

  # -------------------------------------- Plugins
  
  has_secure_password
  
  # -------------------------------------- Associations
  
  has_many :orders
  has_many :reviews
  has_many :items, through: :orders
  
  # -------------------------------------- Validations
  
  validates_presence_of :name, :email
  validates_uniqueness_of :email, case_sensitive: false
  
  # -------------------------------------- Instance Methods
  
  def has_purchased?(item)
    item_ids.include?(item.id)
  end
  
end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  def add
    item = Item.find(params[:item_id])
    current_cart.add_item(item) if item
    redirect_to cart_path, notice: "#{item.title} has been added to your cart"
  end

def remove
  item = Item.find(params[:item_id])
  current_cart.remove_item(item) if item
  redirect_to cart_path, notice: "#{item.title} has been removed from your cart"
end

end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def active_class(url = '')
    'active' if current_page?(url)
  end
  
  def active_section_class(section = '')
    'active' if params[:controller].include?(section)
  end
  
  def bootstrap_class_for(flash_type)
    case flash_type
      when :success
        'alert-success'
      when :error
        'alert-danger'
      when :alert
        'alert-warning'
      when :notice
        'alert-info'
      else
        flash_type.to_s
    end
  end
  
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/marketing_helper.rb
module MarketingHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/orders_helper.rb
module OrdersHelper

  def order_actions(order)
    actions = []
    actions << link_to('Edit', edit_order_path(order))
    actions << link_to('Destroy', order, method: :delete, data: { confirm: 'Are you sure?' })
    actions << link_to('Cancel', transition_order_path(order, 'cancelled')) if order.cancelable?
    actions << link_to('Mark as paid', transition_order_path(order, 'paid')) if order.ordered?
    actions << link_to('Mark as complete', transition_order_path(order, 'completed')) if order.paid?
    actions.join(' | ').html_safe
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dinner Dash<%= ": #{@page_title}" if defined?(@page_title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Dinner Dash</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= content_tag :li, link_to('Items', items_path), class: active_section_class('items') if is_admin? %>
        <%= content_tag :li, link_to('Sales', sales_path), class: active_section_class('sales') if is_admin? %>
        <%= content_tag :li, link_to('Categories', categories_path), class: active_section_class('categories') if is_admin? %>
        <%= content_tag :li, link_to('Users', users_path), class: active_section_class('users') if is_admin? %>
        <%= content_tag :li, link_to('Orders', orders_path), class: active_section_class('orders') if user_signed_in? %>
        <%= content_tag :li, link_to('Menu', menu_index_path), class: active_section_class('menu') %>
        <% unless is_admin? %>
          <%= content_tag :li, link_to('About', about_path), class: active_class(about_path) %>
          <%= content_tag :li, link_to('FAQs', faqs_path), class: active_class(faqs_path) %>
        <% end %>
        <%= content_tag :li, link_to("<i class='glyphicon glyphicon-shopping-cart'></i> <span class='badge'>#{current_cart.items_count}</span>".html_safe, cart_path), class: active_class(cart_path) %>
      </ul>
      <% if current_user %>
        <p class="navbar-text navbar-right">
          Signed in as <%= current_user.email %>.
          <%= link_to 'Edit Account', edit_user_path(current_user.id) %> or
          <%= link_to 'Sign Out', signout_path %>
        </p>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <%= content_tag :li, link_to('Sign In', signin_path), class: active_class(signin_path) %>
          <%= content_tag :li, link_to('Sign Up', signup_path), class: active_class(signup_path) %>
        </ul>
      <% end %>
    </div><!--/.nav-collapse -->
  </div>
</div>

<div class="container">

  <% unless flash.blank? %>
    <% flash.each do |type, message| %>
      <div class="alert <%= bootstrap_class_for(type) %> fade in">
        <button class="close" data-dismiss="alert">×</button>
        <%= message %>
      </div>
    <% end %>
  <% end %>

  <%= yield %>

</div>

<footer>
  <hr />
  <div class="container">
    <p>&copy; 2014 Dinner Dash. All rights reserved.</p>
  </div>
</footer>

</body>
</html>